---
title: "EPL_wet"
format: html
---

#### Set up the Project and import the data

```{r}
# Add packages: 
library(sf)
library(tidyverse)

# Add data

wetlands <- st_read("C:/Users/skownoa/Dropbox/NBAwork/Wetlands/NBA2025_wetl.gpkg")
wetlands <- wetlands %>% mutate(fid = row_number())

pa <- st_read("C:/Users/skownoa/Dropbox/NBAwork/NLC_change/NLC_Change.gdb", layer = "SANBI_PA_2024Q4_Mar2025") 

#ensure it uses proj =  wgs84 aea cm 25 -24 -33
# st_crs(wetlands)
# st_crs(pa)
```

#### Clean up input data

```{r}
# Protected Areas - Subset PA data for 2018 and 2024 using DECL_YEAR, excluding properties degazetted using UNDECL_YEA. In preparation for this selection DECL_YEAR is set to 0 when unknown, and UNDCL_YEA is set to 9999 for those PAs that have never been degazetted.
options(scipen = 999)

pa2018 <- subset(pa, DECL_YEAR <  2019 & UNDECL_YEA >2018)
pa2024 <- subset(pa, DECL_YEAR <  2025 & UNDECL_YEA >2024)

# Wetlands - cleanup data 

## Clean up wetlands  : there are 215 NA in New_name (type) filter these out (future version will name them), make NAs in NBAPES25 into "DD", add zone column  by finding text after _ in the New_name. 



wet <- wetlands %>%
  select(fid,geom, New_name, NBAPES2025, EC18ALL) %>%
  # add area column 
  mutate(area_m2 = as.numeric(st_area(geom))) %>%
  # remove rows with NA in New_name
  filter(!is.na(New_name)) %>% 
  mutate(New_name = str_replace(New_name, "Unchannelled.*", "Unchannelled valley-bottom")
  ) %>%
  # replace underscores inside Drakensberg_Grassland with a space
  mutate(New_name = str_replace(New_name, "Drakensberg_Grassland", "Drakensberg Grassland")) %>%
    # rename some types to include hgm aspect
  mutate(New_name = 
         case_when(New_name == "Indian Ocean Coastal Belt Bioregion" ~ "Maputaland Coastal Belt_Depression",
                   New_name == "Eastern Fynbos-Renosterveld Bioregion" ~ "Eastern Fynbos-Renosterveld_Depression",
                   New_name == "Seashore Vegetation" ~ "Albany Thicket_Depression",                      
                   New_name == "Richtersveld Bioregion" ~ "Karoo Interior_Depression",
                   New_name == "South Strandveld Bioregion" ~ "Southern Fynbos_Depression",
                   New_name == "Mesic Highveld Grassland Group 3" ~ "Mesic Highveld Grassland_Depression",
                   New_name == "Mesic Highveld Grassland Group 4" ~ "Mesic Highveld Grassland_Depression",
                   New_name == "Southern Namib Desert Bioregion" ~ "Karoo Interior_Depression",
                   New_name == "Knersvlakte Bioregion" ~ "Knersvlakte_Depression",
                   New_name == "Gariep Desert Bioregion" ~ "Karoo Interior_Depression",
                   New_name == "Dry Highveld Grassland Group 3" ~ "Dry Highveld Grassland_Depression",
                   New_name == "East Coast Renosterveld Bioregion" ~ "East Coast Renosterveld_Depression",
                   New_name == "South Coast Fynbos Bioregion" ~ "Southern Fynbos_Depression",                                     New_name == "Southern Fynbos Bioregion" ~ "Southern Fynbos_Depression",
                   TRUE       ~ New_name) ) %>%
  # clean up names with "Bioregion" still included (from original naming error)
   mutate(New_name = str_replace(New_name, " Bioregion", "")) %>%
  # clean up Mopani region error
     mutate(New_name = str_replace(New_name, " region", "")) %>%
  # fix spelling of Maputoland better to use Maputaland as in the casewhen
  mutate(New_name = str_replace(New_name, "Maputo", "Maputa")) %>%
  # make a new " hgm" column by getting the text after the _ in New_name
  mutate(hgm = str_extract(New_name, "(?<=_).*")) %>% 
  # make a new "bioregion" col by getting the text before the _ in New_name
  mutate(bioregion = str_extract(New_name, "^[^_]+")) %>%
  # make PES data usable but this will change when Nancy supplies real PES data for depressions and 2018
  mutate(pes24 = ifelse(is.na(NBAPES2025)|NBAPES2025 == "not assessed", "DD", NBAPES2025)) %>%
  mutate(pes18 = ifelse(is.na(EC18ALL), pes24, EC18ALL)) %>% # fill NAs for PES2018 with 2022 values
  select(-NBAPES2025, -EC18ALL) %>%
  rename(type = New_name)

# remove geometry for quicker summaries
wet_tb <- st_drop_geometry(wet)
  
# make a simple table of TYPE and HGM to join with results later 
  type_hgm_tb <- wet %>% select(type, hgm) %>% distinct(type, .keep_all = TRUE) %>%  st_drop_geometry()
```

#### Spatial Analysis

```{r}
# Intersect PA with Wetlands  at each time point
pa18_wet <- st_intersection(wet, pa2018)

pa18_wet <- pa18_wet %>%
  mutate(feature_area18pa = as.numeric(st_area(.))) %>%
   group_by(fid) %>%
  summarise(fid_area18pa = sum((as.numeric(feature_area18pa))), 
            .groups = "drop") %>%
  st_drop_geometry()
  
pa24_wet <- st_intersection(wet, pa2024)
pa24_wet <- pa24_wet %>%
  mutate(feature_area24pa = as.numeric(st_area(.))) %>%
   group_by(fid) %>%
  summarise(fid_area24pa = sum((as.numeric(feature_area24pa))), 
            .groups = "drop") %>%
  st_drop_geometry()

# Join the PA length calculations to the wetland  data (using fid_1) and then group by wetland  type and summarise by Condition class- clean up mismatched PES (Foreign, estuary and Data Defic)
options(scipen = 999)

wet_tb <- wet %>%
  st_drop_geometry() %>%
  left_join(pa24_wet, by = "fid") %>%
  left_join(pa18_wet, by = "fid") %>%
  mutate(across(c(fid_area24pa, fid_area18pa), ~ replace_na(.x, 0)))
    
## Note these data extend outside of SA and into estuaries - these segements need to be filtered out when doing computations. 

```

#### Summarise data per type

```{r}

#summarise by wetland  type including extent per type per condition class - this allows for inclusion of condition in the EPL formula
options(scipen = 999)

# overall type summary
wet_type_18 <- wet_tb %>%
    group_by(type, pes18) %>%
  summarise(extent = sum(as.numeric(area_m2), na.rm = TRUE)) %>%
  ungroup() %>%
  pivot_wider(names_from = pes18, values_from = extent, values_fill = list(extent = 0))  %>%
  mutate(tot_ext18 = rowSums(across(c(A, B, C, D, E, F, DD))))

wet_type_24 <- wet_tb %>%
    group_by(type, pes24) %>%
  summarise(extent = sum(as.numeric(area_m2), na.rm = TRUE)) %>%
  ungroup() %>%
  pivot_wider(names_from = pes24, values_from = extent, values_fill = list(extent = 0))  %>%
  mutate(tot_ext24 = rowSums(across(c(A, B, C, D, E, F, DD))))

# PA x type summary 
 wet_type_pa18 <- wet_tb %>%
    group_by(type, pes18) %>%
  summarise(extent = sum(as.numeric(fid_area18pa), na.rm = TRUE)) %>%
  ungroup()  %>%
  pivot_wider(names_from = pes18, values_from = extent,values_fill = list(extent = 0))  %>%
  mutate(ext_pa18 = rowSums(across(c(A, B, C, D, E, F, DD))))

 wet_type_pa24 <- wet_tb %>%
    group_by(type, pes24) %>%
     summarise(extent = sum(as.numeric(fid_area24pa), na.rm = TRUE)) %>%
  ungroup() %>%
  pivot_wider(names_from = pes24, values_from = extent, values_fill = list(extent = 0)) %>%
  mutate(ext_pa24 = rowSums(across(c(A, B, C, D, E, F, DD))))
  
 # Join the three tables above - this makes a single table in which all the required metrics can be found to compute EPL (note tot ext 18 and to ext 24 are identical )
 
 wet_type_metrics <- wet_type_18 %>%
   select(type, tot_ext18) %>%
   left_join(wet_type_pa18, by = "type") %>%
   rename(A18=A, B18=B, C18=C, D18=D, E18=E, F18=F, DD18 = DD) %>%
   left_join(wet_type_pa24, by = "type") %>%
   mutate(prp_pa18 = ext_pa18/tot_ext18) %>%
   mutate(prp_pa18_ab = (A18 + B18 + DD18)/tot_ext18) %>%
   mutate(prp_pa18_model = (A18 + B18  + DD18 + C18 + (0.5*D18) + (0.3*E18) + (0.1*F18))/tot_ext18) %>%
   mutate(EPL18_all = case_when( prp_pa18 >= 0.3 ~ "WP", 
                                 prp_pa18 >= 0.15 ~ "MP",
                                 prp_pa18 >= 0.015 ~ "PP",
                                 TRUE ~ "NP")) %>% 
   mutate(EPL18_ab = case_when( prp_pa18_ab >= 0.3 ~ "WP", 
                                 prp_pa18_ab >= 0.15 ~ "MP",
                                 prp_pa18_ab >= 0.015 ~ "PP",
                                 TRUE ~ "NP")) %>% 
   mutate(EPL18_model = case_when( prp_pa18_model >= 0.3 ~ "WP", 
                                 prp_pa18_model >= 0.15 ~ "MP",
                                 prp_pa18_model >= 0.015 ~ "PP",
                                 TRUE ~ "NP")) %>%
    #this combines aquatic rule that WP must be ab with the model for repr for MP PP NP
   mutate(EPL18_wp_ab_model = case_when( prp_pa18_ab >= 0.3 ~ "WP", 
                                 prp_pa18_model >= 0.15 ~ "MP",
                                 prp_pa18_model >= 0.015 ~ "PP",
                                 TRUE ~ "NP")) %>%
   mutate(prp_pa24 = ext_pa24/tot_ext18) %>%
   mutate(prp_pa24_ab = (A + B + DD)/tot_ext18) %>%
   mutate(prp_pa24_model = (A + B  + DD + (0.5*C) + (0.3*D) + (0.1*E))/tot_ext18) %>%
   mutate(EPL24_all = case_when( prp_pa24 >= 0.3 ~ "WP", 
                                 prp_pa24 >= 0.15 ~ "MP",
                                 prp_pa24 >= 0.015 ~ "PP",
                                 TRUE ~ "NP")) %>% 
   mutate(EPL24_ab = case_when( prp_pa24_ab >= 0.3 ~ "WP", 
                                 prp_pa24_ab >= 0.15 ~ "MP",
                                 prp_pa24_ab >= 0.015 ~ "PP",
                                 TRUE ~ "NP")) %>% 
   mutate(EPL24_model = case_when( prp_pa24_model >= 0.3 ~ "WP", 
                                 prp_pa24_model >= 0.15 ~ "MP",
                                 prp_pa24_model >= 0.015 ~ "PP",
                                 TRUE ~ "NP"))   %>%
    #this combines aquatic rule that WP must be ab with the model for repr for MP PP NP
   mutate(EPL24_wp_ab_model = case_when( prp_pa24_ab >= 0.3 ~ "WP", 
                                 prp_pa24_model >= 0.15 ~ "MP",
                                 prp_pa24_model >= 0.015 ~ "PP",
                                 TRUE ~ "NP"))   %>%
 # add in HGM type
   left_join(type_hgm_tb, by = "type")
    
 
  # export a csv of results - Condition and EPL per river type 2018 and 2024
   write.csv(wet_type_metrics, file = "outputs/epl_wet_metrics_per_type.csv")
```

#### Output tables

```{r}
# 2018 summaries
# make summary counts of EPL categories per HGM
 epl18_sum <- wet_type_metrics %>%
    group_by(EPL18_wp_ab_model, hgm) %>%
  summarise(count = n(),.groups = 'drop') %>%
  pivot_wider(names_from = EPL18_wp_ab_model, 
              values_from = count, values_fill = 0) %>%
  relocate(WP, .before = MP)%>%
  relocate(NP, .after = PP) %>%
   # Add row-wise TOTAL
  rowwise() %>%
  mutate(Total = sum(c_across(where(is.numeric)))) %>%
  ungroup() %>%
  # Add TOTAL row (column-wise sums)
  bind_rows(summarise(., hgm = "Total", across(where(is.numeric), sum))) %>%
  # Add EPLindex
  mutate(EPLI = ((WP*3)+(MP*2)+(PP*1)+(NP*0))/((WP+MP+PP+NP)*3)) %>%
    mutate(hgm = factor(hgm, levels = c("Total", "Unchannelled valley-bottom" , "Seep", "Floodplain","Depression"))) %>% ## ggplot plots inverted factors!
   arrange(hgm)
 
 # export a csv of results - COUNT of EPL 18 per slope zone
 write.csv(epl18_sum, file = "outputs/epl18_wet_sum_count.csv") 
 
  # make summary of extent of EPL
 epl18_sum_ext <- wet_type_metrics %>%
    group_by(EPL18_wp_ab_model, hgm) %>%
  summarise(extent = round(sum(tot_ext18)/1000000, 0),.groups = 'drop') %>%
  pivot_wider(names_from = EPL18_wp_ab_model, 
              values_from = extent, values_fill = 0) %>%
  relocate(WP, .before = MP)%>%
  relocate(NP, .after = PP) %>%
   # Add row-wise TOTAL
  rowwise() %>%
  mutate(Total = sum(c_across(where(is.numeric)))) %>%
  ungroup() %>%
  # Add TOTAL row (column-wise sums)
  bind_rows(summarise(., hgm = "Total", across(where(is.numeric), sum))) %>%
    mutate(hgm = factor(hgm, levels = c("Total", "Unchannelled valley-bottom" , "Seep", "Floodplain","Depression"))) %>% ## ggplot plots inverted factors!
   arrange(hgm)
 
 # export a csv of results - EXTENT (km) of EPL 18 per slope zone
  write.csv(epl18_sum_ext, file = "outputs/epl18_wet_sum_ext.csv")

  # Convert extent per epl category to proportion 
  epl18_sum_prpext <- epl18_sum_ext %>%
  filter(hgm != "Total") %>%
  mutate(across(c(WP, MP, PP, NP), ~ round(.x / Total, 3))) %>%
  select(hgm, WP, MP, PP, NP)
  
  # export a csv of results - PROPORTIONAL EXTENT  (km) of EPL 18 per slope zone
   write.csv(epl18_sum_prpext, file = "outputs/epl18_wet_sum_prp.csv")
 
  # 2024 summaries
  # make summary counts of EPL
  epl24_sum <- wet_type_metrics %>%
    group_by(EPL24_wp_ab_model, hgm) %>%
  summarise(count = n(),.groups = 'drop') %>%
  pivot_wider(names_from = EPL24_wp_ab_model, 
              values_from = count, values_fill = 0) %>%
  relocate(WP, .before = MP)%>%
  relocate(NP, .after = PP) %>%
   # Add row-wise TOTAL
  rowwise() %>%
  mutate(Total = sum(c_across(where(is.numeric)))) %>%
  ungroup() %>%
  # Add TOTAL row (column-wise sums)
  bind_rows(summarise(., hgm = "Total", across(where(is.numeric), sum))) %>%
  # Add EPLindex
  mutate(EPLI = ((WP*3)+(MP*2)+(PP*1)+(NP*0))/((WP+MP+PP+NP)*3)) %>%
     mutate(hgm = factor(hgm, levels = c("Total", "Unchannelled valley-bottom" , "Seep", "Floodplain","Depression"))) %>% ## ggplot plots inverted factors!
   arrange(hgm)
  
 # export a csv of results - COUNT of EPL 18 per slope zone
 write.csv(epl24_sum, file = "outputs/epl24_wet_sum_count.csv") 
 
 # make summary of extent of EPL
 epl24_sum_ext <- wet_type_metrics %>%
    group_by(EPL24_wp_ab_model, hgm) %>%
  summarise(extent = round(sum(tot_ext18)/1000000, 0),.groups = 'drop') %>%
  pivot_wider(names_from = EPL24_wp_ab_model, 
              values_from = extent, values_fill = 0) %>%
  relocate(WP, .before = MP)%>%
  relocate(NP, .after = PP) %>%
   # Add row-wise TOTAL
  rowwise() %>%
  mutate(Total = sum(c_across(where(is.numeric)))) %>%
  ungroup() %>%
  # Add TOTAL row (column-wise sums)
  bind_rows(summarise(., hgm = "Total", across(where(is.numeric), sum))) %>%
    mutate(hgm = factor(hgm, levels = c("Total", "Unchannelled valley-bottom" , "Seep", "Floodplain","Depression"))) %>% ## ggplot plots inverted factors!
   arrange(hgm)
 
 # export a csv of results - EXTENT (km) of EPL 18 per slope zone
  write.csv(epl24_sum_ext, file = "outputs/epl24_wet_sum_ext.csv")
 
 epl24_sum_prpext <- epl24_sum_ext %>%
  filter(hgm != "Total") %>%
  mutate(across(c(WP, MP, PP, NP), ~ round(.x / Total, 3))) %>%
  select(hgm, WP, MP, PP, NP)
 
 # export a csv of results - PROPORTIONAL EXTENT  (km) of EPL 18 per slope zone
   write.csv(epl24_sum_prpext, file = "outputs/epl24_wet_sum_prp.csv")
```

#### **Make graphs for NBA**

```{r}

# load nbaR package : first run this in console devtools::install_github("SANBI-NBA/nbaR") 
library(nbaR)

# Use NBA package to make EPL graph (need high res output for booklet)
EPL24count <- epl24_sum %>%
    rename(`Well Protected` = WP, 
           `Moderately Protected` = MP, 
           `Poorly Protected` = PP, 
           `Not Protected` = NP ) # %>%
  # select(-...1) # required if importing from CSV
 
epl24_bar_plot_count <- nba_plot(EPL24count,
                  `hgm`,
                  2:5,
                 CHRT = "bar",
                 NUM = TRUE,
                 LAB = "Percentage of ecosystem types",
                SAVE = NULL, 
                SCALE_TEXT = 0.6)

epl24_bar_plot_count <- epl24_bar_plot_count +
  theme(
    legend.position = "bottom",             # keep it at the bottom
    legend.margin = margin(l = -45, r = -5, t = -5, b = -5)) 

#export the graph
ggsave(
  filename = "outputs/epl24_wet_bar_plot_count.jpeg", # File name
  plot = epl24_bar_plot_count,                  # Plot object
  device = "jpeg",                        # File format
  width = 16, height = 12, units = "cm",   # Dimensions
  dpi = 300                               # Resolution
)

# graphs for extent per slope zone per epl category

EPL24ext <- epl24_sum_ext %>%
    rename(`Well Protected` = WP, 
           `Moderately Protected` = MP, 
           `Poorly Protected` = PP, 
           `Not Protected` = NP ) # %>%
  # select(-...1) # required if importing from CSV
 
epl24_bar_plot_ext <- nba_plot(EPL24ext,
                  `hgm`,
                  2:5,
                 CHRT = "bar",
                 NUM = FALSE,
                 LAB = "Percentage of ecosystem extent",
                SAVE = NULL, 
                SCALE_TEXT = 0.6)


epl24_bar_plot_ext <- epl24_bar_plot_ext +
  theme(
    legend.position = "bottom",             # keep it at the bottom
    legend.margin = margin(l = -45, r = -5, t = -5, b = -5))

#export the graph
ggsave(
  filename = "outputs/epl24_wet_bar_plot_ext.jpeg", # File name
  plot = epl24_bar_plot_ext,                   # Plot object
  device = "jpeg",                        # File format
  width = 16, height = 12, units = "cm",   # Dimensions
  dpi = 300                               # Resolution
)

# Make a line plot of EPL Index using 2018 and 2014 timepoints - request Natasha to impve this or add to package.

EPLI <- epl24_sum %>%
  select(hgm, EPLI) %>% 
  rename(EPLI24 = EPLI) %>%
   left_join(epl18_sum, by ="hgm") %>%
   rename(EPLI18 = EPLI) %>%
   rename(HGMzone = hgm) %>%
  select(HGMzone,EPLI18, EPLI24) %>%
  pivot_longer(cols = c(2,3), names_to = "Year", values_to = "EPLI") %>%
    mutate(Year = case_when(
    Year == "EPLI18" ~ "2018",
    Year == "EPLI24" ~ "2024",
    TRUE ~ Year
  ))
  
 epli_line_plot <- ggplot(EPLI, aes(x = Year, y = EPLI, group = HGMzone)) +
  geom_line(aes(linetype = HGMzone, color = HGMzone), linewidth = 1.2) +
  geom_point(aes(color = HGMzone), size = 2) +
  theme_minimal() +
  labs(x = "Year", y = "EPLI") +
  scale_x_discrete(limits = c("2018", "2024")) +
  scale_color_manual(values = c(
    "Total" = "black",
    "Floodplain" = "blue",
    "Unchannelled valley-bottom" = "darkgreen",
    "Depression" = "brown",
    "Seep" = "orange"
  )) + 
  coord_cartesian(ylim = c(0.1, 0.5)) +
    guides(color = guide_legend(reverse = TRUE),
         linetype = guide_legend(reverse = TRUE)) +
  theme(legend.title = element_blank())
  
   
  epli_line_plot
  
  #export the graph
ggsave(
  filename = "outputs/epli_riv_line_plot.jpeg", # File name
  plot = epli_line_plot,                   # Plot object
  device = "jpeg",                        # File format
  width = 16, height = 12, units = "cm",   # Dimensions
  dpi = 300                               # Resolution
)
```
